### ISSUE TITLE
Viewprofile support

### ISSUE THREAD

**Issue by Galixte** [gouarfig/phpBB-joined-date-format#1]
Hi @gouarfig,

could you add the support for viewprofile page ?

**Comment by gouarfig** [comment]
Hi,

Have you tried this other extension?
https://www.phpbb.com/customise/db/extension/joined_date_format/

When I was searching for this extension I couldn't find it for some reason, hence why I started to do mine. But this other one is more advanced than mine, so I kind-of abandonned the development of it.

Is this other one fitting your needs?

**Comment by Galixte** [comment]
Hi,

i was thinking there was no extension for that on phpbb.com, thanks for informations.
